package com.hello.mapper;

import com.hello.model.LoginHistory;
import com.hello.model.LoginHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int countByExample(LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int deleteByExample(LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int insert(LoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int insertSelective(LoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    List<LoginHistory> selectByExample(LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    LoginHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") LoginHistory record, @Param("example") LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int updateByExample(@Param("record") LoginHistory record, @Param("example") LoginHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int updateByPrimaryKeySelective(LoginHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_history
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int updateByPrimaryKey(LoginHistory record);
}