package com.hello.mapper;

import com.hello.model.PurchaseOrder;
import com.hello.model.PurchaseOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PurchaseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int countByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int deleteByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int insert(PurchaseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int insertSelective(PurchaseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    List<PurchaseOrder> selectByExample(PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    PurchaseOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") PurchaseOrder record, @Param("example") PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int updateByExample(@Param("record") PurchaseOrder record, @Param("example") PurchaseOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int updateByPrimaryKeySelective(PurchaseOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    int updateByPrimaryKey(PurchaseOrder record);
}