package com.hello.model;

import java.util.Date;

public class LoginHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.user_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.last_date
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Date lastDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_history.last_ip
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String lastIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.id
     *
     * @return the value of login_history.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.id
     *
     * @param id the value for login_history.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.user_id
     *
     * @return the value of login_history.user_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.user_id
     *
     * @param userId the value for login_history.user_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.last_date
     *
     * @return the value of login_history.last_date
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Date getLastDate() {
        return lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.last_date
     *
     * @param lastDate the value for login_history.last_date
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setLastDate(Date lastDate) {
        this.lastDate = lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_history.last_ip
     *
     * @return the value of login_history.last_ip
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_history.last_ip
     *
     * @param lastIp the value for login_history.last_ip
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }
}