package com.hello.model;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.weight
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.short_desc
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String shortDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.image
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Float stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.live
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Boolean live;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.unlimited
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Boolean unlimited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.location
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.long_desc
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String longDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.weight
     *
     * @return the value of product.weight
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.weight
     *
     * @param weight the value for product.weight
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.short_desc
     *
     * @return the value of product.short_desc
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getShortDesc() {
        return shortDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.short_desc
     *
     * @param shortDesc the value for product.short_desc
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc == null ? null : shortDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.image
     *
     * @return the value of product.image
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.image
     *
     * @param image the value for product.image
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Float getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setStock(Float stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.live
     *
     * @return the value of product.live
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Boolean getLive() {
        return live;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.live
     *
     * @param live the value for product.live
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setLive(Boolean live) {
        this.live = live;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.unlimited
     *
     * @return the value of product.unlimited
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Boolean getUnlimited() {
        return unlimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.unlimited
     *
     * @param unlimited the value for product.unlimited
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setUnlimited(Boolean unlimited) {
        this.unlimited = unlimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.location
     *
     * @return the value of product.location
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.location
     *
     * @param location the value for product.location
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.long_desc
     *
     * @return the value of product.long_desc
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getLongDesc() {
        return longDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.long_desc
     *
     * @param longDesc the value for product.long_desc
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc == null ? null : longDesc.trim();
    }
}