package com.hello.model;

public class PurchaseOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.create_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.user_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.status
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.update_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.total_price
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order.discount
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    private String discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.id
     *
     * @return the value of purchase_order.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.id
     *
     * @param id the value for purchase_order.id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.create_time
     *
     * @return the value of purchase_order.create_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.create_time
     *
     * @param createTime the value for purchase_order.create_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.user_id
     *
     * @return the value of purchase_order.user_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.user_id
     *
     * @param userId the value for purchase_order.user_id
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.status
     *
     * @return the value of purchase_order.status
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.status
     *
     * @param status the value for purchase_order.status
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.update_time
     *
     * @return the value of purchase_order.update_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.update_time
     *
     * @param updateTime the value for purchase_order.update_time
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.total_price
     *
     * @return the value of purchase_order.total_price
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.total_price
     *
     * @param totalPrice the value for purchase_order.total_price
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.discount
     *
     * @return the value of purchase_order.discount
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.discount
     *
     * @param discount the value for purchase_order.discount
     *
     * @mbggenerated Fri Jun 17 00:14:52 CST 2016
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }
}